export const FEATURE_DEFINITIONS = {
  VOLUME: 'Volume',
  GENDER: 'Gender',
  HEIGHT: 'Height',
  WEIGHT: 'Weight',
  AGE: 'Age',
  VCI_SUPRA: 'VCI Suprarenal',
  VCI_VENO: 'VCI Venoatrial',
} as const;

export type FeatureKey = keyof typeof FEATURE_DEFINITIONS;
export type FeatureName = typeof FEATURE_DEFINITIONS[FeatureKey];

export const ALL_FEATURES: FeatureName[] = [
  FEATURE_DEFINITIONS.VOLUME,
  FEATURE_DEFINITIONS.GENDER,
  FEATURE_DEFINITIONS.HEIGHT,
  FEATURE_DEFINITIONS.WEIGHT,
  FEATURE_DEFINITIONS.AGE,
  FEATURE_DEFINITIONS.VCI_SUPRA,
  FEATURE_DEFINITIONS.VCI_VENO,
];

export const REQUIRED_FEATURES = [
  FEATURE_DEFINITIONS.VOLUME,
  FEATURE_DEFINITIONS.GENDER,
];

export const MODEL_FEATURES = {
  linear: [FEATURE_DEFINITIONS.VOLUME, FEATURE_DEFINITIONS.GENDER],
  mlp: [FEATURE_DEFINITIONS.VOLUME, FEATURE_DEFINITIONS.GENDER, FEATURE_DEFINITIONS.VCI_SUPRA],
  ridge: {
    partial: [FEATURE_DEFINITIONS.VOLUME, FEATURE_DEFINITIONS.GENDER, FEATURE_DEFINITIONS.VCI_SUPRA],
    full: [
      FEATURE_DEFINITIONS.VOLUME,
      FEATURE_DEFINITIONS.GENDER,
      FEATURE_DEFINITIONS.AGE,
      FEATURE_DEFINITIONS.VCI_SUPRA,
      FEATURE_DEFINITIONS.VCI_VENO,
    ],
    body_simple: [
      FEATURE_DEFINITIONS.VOLUME,
      FEATURE_DEFINITIONS.GENDER,
      FEATURE_DEFINITIONS.HEIGHT,
      FEATURE_DEFINITIONS.WEIGHT,
    ],
    body_full: [
      FEATURE_DEFINITIONS.VOLUME,
      FEATURE_DEFINITIONS.GENDER,
      FEATURE_DEFINITIONS.AGE,
      FEATURE_DEFINITIONS.HEIGHT,
      FEATURE_DEFINITIONS.WEIGHT,
    ],
    all: [
      FEATURE_DEFINITIONS.VOLUME,
      FEATURE_DEFINITIONS.GENDER,
      FEATURE_DEFINITIONS.HEIGHT,
      FEATURE_DEFINITIONS.WEIGHT,
      FEATURE_DEFINITIONS.AGE,
      FEATURE_DEFINITIONS.VCI_SUPRA,
      FEATURE_DEFINITIONS.VCI_VENO,
    ],
  },
} as const;
